name: Viewer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: 1

jobs:
  build-viewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install rust toolchain
        run: |
          rustup toolchain install nightly --profile minimal
          rustup override set nightly
          rustup target add wasm32-unknown-unknown

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install Trunk
        run: cargo install trunk

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm dependencies
        working-directory: viewer
        run: npm install

      - name: Build viewer
        working-directory: viewer
        run: trunk build
